[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
