[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
